<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Obase对象数据模型配置生成器WorkFlow.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.17.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Obase.OdmGenerator.Agent\Obase.OdmGenerator.Agent.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
